### ISSUE TITLE
Refactoring utils.py file to be more readable and clean.

### ISSUE THREAD

**Issue by mklevk** [Starenesha/django-prj-test#4]
Hi Olga.

Could you do the last request, please?

In my opinion, the code in the function 'consumption' in utils.py file is not clean and readable enough:

```
def consumption(records):
    records_ =records[:]

    tmp_value = []
    for x in records:
        tmp = x.value
        tmp_value.append(tmp)
        records = x

    tmp_date = []


    for x in records_:
        tmp = x.date.isoformat()
        tmp_date.append(tmp)
        records_ = x

    tmp_date_ = tmp_date[1:]

    lst_consumption = []
    diff = [tmp_value[n - 1] - tmp_value[n] for n in range(1, len(tmp_value))]
    result_lst = list(zip(tmp_date, tmp_date_, diff))
    return result_lst
```

At first glance it's not clear why the 'records_' variable is needed here:

 `records_ =records[:]`

and the same with 'lst_consumption' variable, it is not used:

`lst_consumption = []`

Could you refactor this function and make it more clean and more readable, please? 

Thanks,
Mykola.

**Comment by Starenesha** [comment]
Hi, @LevchenCoM !
this function create  list of tuples with consumption and date - for chart.
first loop - creates a list with all values
second cycle - creates a list with date 

get out of the first loop, 'records' saves as 'records = x'
so, i used to slice - records_ =records[:] to use in the second cycle.
I added some comments.

Can you tell me please, needed rewrite the implementation of this function? or required make two other functions ( performing of calculation consumptions and another function - data for chart)

**Comment by mklevk** [comment]
Hi @Starenesha ,

> get out of the first loop, 'records' saves as 'records = x'

Changing the variable we iterate over is not very good.

Could you reduce number of loops to one?
In input we have list with tuples (va1, var2) and in this function we should calculate and add only one variable to the new list. I think we can do it in one loo, it will be more readable. 
So could you rewrite this function?

Please, tell me if you have any questions.
Thanks,
Mykola.

**Comment by Starenesha** [comment]
Hi @LevchenCoM ,
i rewrite function and removed one loop from the function
